services:
  guacd:
    container_name: guacd_app
    image: guacamole/guacd:1.6.0
    restart: unless-stopped

  guac-sql:
    container_name: guac-sql_app
    image: mysql:8.0
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "${GUAC_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: "${GUAC_DB_PASSWORD}"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/initdb.sql
      - guac-db-data:/var/lib/mysql

  guac_web:
    container_name: guac_web_app
    image: guacamole/guacamole:1.6.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: guacamole_db
      MYSQL_HOSTNAME: guac-sql
      MYSQL_PASSWORD: "${GUAC_DB_PASSWORD}"
      MYSQL_USER: guacamole_user
      GUACD_HOSTNAME: guacd
      JSON_SECRET_KEY: "${GUACAMOLE_JSON_SECRET_KEY}"
    volumes:
      - ./branding/portal-branding.jar:/etc/guacamole/extensions/portal-branding.jar:ro
    depends_on:
      - guac-sql
      - guacd

volumes:
  guac-db-data:
