services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai

  guac-sql:
    container_name: guac-sql
    image: mysql:8
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: xran
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: xran
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - /home/xran/data:/var/lib/mysql
    ports:
      - "127.0.0.1:33060:3306"

  guac_web:
    container_name: guac_web
    image: guacamole/guacamole
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: guacamole_db
      MYSQL_HOSTNAME: guac-sql
      MYSQL_PASSWORD: xran
      MYSQL_USER: guacamole_user
      GUACD_HOSTNAME: guacd
      JSON_SECRET_KEY: "4c0b569e4c96df157eee1b65dd0e4d41"
      WEBAPP_CONTEXT: "ROOT"
    volumes:
      - ./branding/portal-branding.jar:/etc/guacamole/extensions/portal-branding.jar:ro
    depends_on:
      - guac-sql
      - guacd
